---
abstract: 'write your linewise code for handles; this does the rest'
author:
  - 'Ricardo SIGNES, C<< <rjbs@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Mixin::Linewise
name: Mixin-Linewise
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  IO::File: 0
  IO::String: 0
  Sub::Exporter: 0.9
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.003
